version: '3.7'

services:
  # PHP-FPM container
  php:
    build: .
    container_name: symfony_php
    volumes:
      - .:/var/www
    networks:
      - symfony_net
    working_dir: /var/www
    expose:
      - "9000"
    environment:
      - PHP_MEMORY_LIMIT=512M

  # Nginx container
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony_net

  # Database container (MySQL)
  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:
    driver: local
